# Generated by Django 4.0.6 on 2022-08-14 21:12

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='adress1',
            new_name='address',
        ),
        migrations.RenameField(
            model_name='order',
            old_name='phone',
            new_name='country',
        ),
        migrations.RenameField(
            model_name='order',
            old_name='full_name',
            new_name='first_name',
        ),
        migrations.RenameField(
            model_name='order',
            old_name='post_code',
            new_name='postal_code',
        ),
        migrations.RemoveField(
            model_name='order',
            name='adress2',
        ),
        migrations.RemoveField(
            model_name='order',
            name='billing_status',
        ),
        migrations.RemoveField(
            model_name='order',
            name='order_key',
        ),
        migrations.RemoveField(
            model_name='order',
            name='total_paid',
        ),
        migrations.RemoveField(
            model_name='order',
            name='user',
        ),
        migrations.AddField(
            model_name='order',
            name='email',
            field=models.EmailField(default="", max_length=254),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='order',
            name='last_name',
            field=models.CharField(default="", max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='order',
            name='note',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('Created', 'Created'), ('Processing', 'Processing'), ('Shipped', 'Shipped'), ('Ready for pickup', 'Ready for pickup'), ('Completed', 'Completed')], default='Created', max_length=20),
        ),
        migrations.AddField(
            model_name='order',
            name='telephone',
            field=models.CharField(default="", max_length=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='order',
            name='transport',
            field=models.CharField(choices=[('Courier delivery', 'Courier delivery'), ('Recipient pickup', 'Recipient pickup')], default="", max_length=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='order',
            name='transport_cost',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
            preserve_default=False,
        ),
    ]
